export default {
  LOAD_STARTED: "LOAD_STARTED",
  LOAD_SUCCEEDED: "LOAD_SUCCEEDED",
  LOAD_FAILED: "LOAD_FAILED",

  ADD_STARTED: "ADD_STARTED",
  ADD_SUCCEEDED: "ADD_SUCCEEDED",
  ADD_FAILED: "ADD_FAILED",

  UPDATE_STARTED: "UPDATE_STARTED",
  UPDATE_SUCCEEDED: "UPDATE_SUCCEEDED",
  UPDATE_FAILED: "UPDATED_FAILED",

  DELETE_STARTED: "DELETE_STARTED",
  DELETE_SUCCEEDED: "DELETE_SUCCEEDED",
  DELETE_FAILED: "DELETED_FAILED",

  CLEAR_CHECKED_STARTED: "CLEAR_CHECKED_STARTED",
  CLEAR_CHECKED_SUCCEEDED: "CLEAR_CHECKED_SUCCEEDED",
  CLEAR_CHECKED_FAILED: "CLEAR_CHECKED_FAILED",
};
